### ISSUE TITLE
Gearscript: gear Sniper toevoegen

### ISSUE THREAD

**Issue by WhistleTDNL** [Lowlands-Tactical/LT_Template_3G.VR#11]
- [x] Dagr
- [x] Vector
- [x] Kestrel
- [x] Atraq
- [x] Batteries voor vector??

**Comment by WhistleTDNL** [comment]
Tevens sportief scope eruit

**Comment by Ligthert** [comment]
Batterijen zijn niet nodig. 
Spotting scope ook niet.

**Comment by WhistleTDNL** [comment]
heb de spottingscope erin laten zitten voor bij de spotter.

**Comment by WhistleTDNL** [comment]
done
