### ISSUE TITLE
Fatigue parameter toevoegen aan mod

### ISSUE THREAD

**Issue by WhistleTDNL** [Lowlands-Tactical/LT_Template_3G.VR#12]
Fatigue parameter toevoegen

- [x]  Onplayerrespawn.sqf

- [x] init.sqf

- [x] doorvoeren in params

**Comment by Ligthert** [comment]
Dit moet uiteraard vanuit _base. :) ( iets met conmon in de bestandsnaam. )

Als je in wild ravens de initServer.sqf bekijkt dan zie je welke mooie bis-functie hier het geschiktst voor is. :)

**Comment by WhistleTDNL** [comment]
done
