### ISSUE TITLE
Parameters zorgen ervoor dat mods crashen

### ISSUE THREAD

**Issue by WhistleTDNL** [Lowlands-Tactical/LT_Template_3G.VR#14]
Als er in de parameters iets wordt aangepast zorgt dat voor een crash van de modset. Alle mods werken dan helaas niet meer.

Het zit m waarschijnlijk in een van de onderstaande parameters:

- [ ] Time of day

- [ ] Weer

- [ ] Fog

**Comment by Ligthert** [comment]
Dit wordt een scenario pakken en dit op de server testen door 1 voor 1 een parameter aan te passen totdat je weet welke het is. En van daaruit uit zien te vinden waarom ie dat doet... :s

**Comment by WhistleTDNL** [comment]
Dit is de error die hij gooit:

`18:08:22 Error in expression <_date = date;`
`_date set [3,_timeOfDay];`
`_data set [4,"00"];`
`[_date,true,fal>`
`18:08:22   Error position: <_data set [4,"00"];`
`[_date,true,fal>`
`18:08:22   Error Undefined variable in expression: _data`
`18:08:22 File lt_template_base\functions\fn_setTime.sqf, line 23`

**Comment by WhistleTDNL** [comment]
fixed met [https://github.com/Lowlands-Tactical/LT_Template_Base/commit/0f5a0196d6f70adf717e83d161474067733faecc](url)
