### ISSUE TITLE
Map issue

### ISSUE THREAD

**Issue by WhistleTDNL** [Lowlands-Tactical/LT_Template_3G.VR#15]
De rollen CO en DC krijgen geen kaart. We weten helaas nog niet waarom.
Bij mij is op dit moment het 1 keer voorgekomen en dat was omdat ik mijn scenario van de oude naar de nieuwe template over had gezet. Meerdere malen geprobeerd om e.e.a te reproduceren op persoonlijke dedicated server maar het is niet gelukt om de error te krijgen.

**Comment by Ligthert** [comment]
Gear related. Maptools is eruit en het is nog geen issue. Wellicht dat we meer in de backpacks moeten douwen.

**Comment by WhistleTDNL** [comment]
Het lijkt toch meer een initialisatie dingetje te zijn. Het is niet specifiek voor bepaalde rollen (zoals CO en DC). We hebben van Clavus en Sacha rpt-logs gehad maar daaruit kwam helaas geen duidelijkheid. 

Met commit [https://github.com/Lowlands-Tactical/LT_Template_Base/commit/67c01861d1eb4617a3844f0c49209254575cd471](67c0186) zou het opgelost kunnen zijn. Let's see met de komende gamesessies.

**Comment by Ligthert** [comment]
Dit is niet meer gesignaleerd (net aan de staf gevraagd). Als het weer voorkomt dan is de debug wat uitgebreider en kunnen we het dan uitzoeken waar het aan licht. Ik sluit daarom dit ticket.
