### ISSUE TITLE
Attribuut in 3den voor crates en voertuigen om de gear te bepalen

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#19]
Dit moet op dit moment nog met de hand, maar ik denk dat de F3 aanpak wel een goede is.
- verschillende type crates
- verschillende type voertuigen

**Comment by WhistleTDNL** [comment]
klaar met https://github.com/Lowlands-Tactical/LT_Template_Base/commit/0d92dd776fd111c4461d6f65e4d178981b43cd54
