### ISSUE TITLE
De optie geven voor units om stil te staan 

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#20]
Voor niet-speler eenheden de mogelijkheid geven om een de optie "static" oid aan te vinken wat deze code uitvoert:
`this addEventHandler ["Animchanged",{(_this select 0) setunitpos "up"}]; this allowFleeing 0; this forceSpeed 0;`

Dit is handig voor ventjes in bunkers en huisjes.

**Comment by WhistleTDNL** [comment]
Gedaan met https://github.com/Lowlands-Tactical/LT_Template_Base/commit/0d92dd776fd111c4461d6f65e4d178981b43cd54

De eventhandler heb ik eruit gelaten, zodat je binnen 3DEN nog wel kunt kiezen welke stance. ArmA is nog wel ArmA en laat de unit soms dekking zoeken door te gaan liggen of zitten.
