### ISSUE TITLE
Onvoldoende magazijnen/clips voor de gemiddelde sessie

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#21]
Gezien we van MILSIM naar meer een PewPew speelstijl zijn gegaan hebben we nu meer magazijnen nodig. En meer magazijnen in de rugtas ipv de camo en de vest, want ik vermoed dat dit de 152 voorkomt bij de GC/VTL omdat deze al vol zijn.

**Comment by WhistleTDNL** [comment]
Flendurs geeft [hier](https://lowtac.slack.com/archives/template/p1476109248000017) aan dat zij nog moeten kijken of er meer gear in de units wordt geplaatst, of dat er resupplies worden geregeld.

**Comment by Ligthert** [comment]
Gisteren met @Flendurs en @ancorb1974 dit kort besproken:

- @Flendurs Flenders melde dat via combat support extra ammo opvragen op het slagveld gameplay voor een lange tijd stil legt en dat het interessanter is om te kijken of extra ammo wat gedragen wordt en hoe dat met de fatigue afgehandelt moet worden (ofzo)
- @ancorb1974 Had de fatique effectief uitgezet en wordt vanuit de server geregeld

**Comment by Ligthert** [comment]
Na wat speurwerk aan mijn kant is de fatique gedeelte gefixed! :)

Nu nog ammo overhevelen van het uniform en vest naar de backpack.

**Comment by WhistleTDNL** [comment]
Met [deze](https://github.com/Lowlands-Tactical/LT_Template_Base/commit/2231fb7a6baf0eb33257d5efd6f2ce44efc66c58) commit kunnen we monitoren hoe zwaar de rollen zijn. Er wordt in de RPT een dosis spam gezet die kan aantonen welke gewichten (in KG) er in de camo, het vest en de backpack zit. Dit wordt dan tegenover de maximale capiciteit gezet zodat we kunnen zien of de rol te zwaar is bepakt. 

Hopelijk kunnen we op die manier kijken welke rollen meer gaar kunnen dragen en welke rollen teveel gaar hebben.

Volgens mij was de regel tussen de 30 en 35 kg uit te komen.

**Comment by Ligthert** [comment]
Na overleg, afwezigheid van klachten en over het algemeen een goede ervaring is dit niet echt een issue meer. Dicht.
