### ISSUE TITLE
ACE3 Medic nalopen in units

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#22]
Ze zijn nu een warboel en een harble garble en de medic is geen medic en andere units weer wel. :-(

**Comment by Ligthert** [comment]
Nog niet gechecked.
Ook geen commits de laatste tijd die hierover gaan.

**Comment by WhistleTDNL** [comment]
Geen idee wat ik hiermee zou moeten doen. Dit ligt volgens mij meer in de handen van degenen die bij de ACE serversettings kan...
