### ISSUE TITLE
Medium AT

### ISSUE THREAD

**Issue by ancorb1974** [Lowlands-Tactical/LT_Template_3G.VR#28]
Ik zag net dat een medium anti tank 3 missiles in zijn backpack had en 1 in zijn launcher, 
door ace is de PCML launcher die gebruikt word maar een enkel shots wapen.
Hierdoor heeft hij 3 missiles onnodig bij hem en hij heeft 45 kilo bij hem :wink:

**Comment by WhistleTDNL** [comment]
Gefixt met https://github.com/Lowlands-Tactical/LT_Template_Base/commit/5d1894efd91daa796d2f108772ded64b72b8183f
