### ISSUE TITLE
NLD_Units_80

### ISSUE THREAD

**Issue by ancorb1974** [Lowlands-Tactical/LT_Template_3G.VR#33]
Nieuwe faction in NLD_Units
Deze heeft een andere load out 
Wapen zonder scope is de belangrijkste aanpassing hierin.
Ook engineer en grenadier hebben een andere wapen.

**Comment by WhistleTDNL** [comment]
Dit is af te handelen via customGear.sqf en description.ext. De uitleg daarover staat op het forum.
