### ISSUE TITLE
De SLA kan niet bij nacht werken

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#34]
Op dit moment is de sight van de SLA niet compatible met de NVGs. Dit maakt hem ineffectief tijdens nacht-operaties waar een NVG vereist is.

Dit kan opgelost worden op 2 manier:
# SLA krijgt een sight die NVG compatible is
# SLA krijgt een NVG sight in de rugtas

**Comment by WhistleTDNL** [comment]
klaar met [deze](7076e4d8325d495c3ff119f3bcbc0c30ad6d9545) commit
