### ISSUE TITLE
Server stats links onder in de kaart

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#36]
Dit had ik tijdens de Joint-OP begin Maart, namelijk een marker die elke minuut geupdate werd met daarin de text hoeveel FPS, CPS, Local AI en Remote AI (Zeus).

**Comment by WhistleTDNL** [comment]
Is dit al gelukt?

**Comment by Ligthert** [comment]
Moet ik nog aan beginnen. Het heeft een beetje lage prio tenopzichte van CRAPPY PERFORMANCE OP BIS MAPS!

**Comment by Ligthert** [comment]
Ik zal er vanvond is naar kijken. Ik denk dat ik de grote pre-overhaul dingen zoals facties en camos al afgehandeld heb.

**Comment by Ligthert** [comment]
And done. Basic ding zit erin. Kan altijd uitgebreid worden. Voor nu is dit genoeg voor spelers om bij de admin/missiemaker te klagen.
