### ISSUE TITLE
Eenmalige teleport voor 'leaders'

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#38]
Denk aan PDs waar de GCs kunnen kiezen waar ze beginnen. Dit is bijvoorbeeld een TownSweep of een COOP scenario in de toekomst.

Dit hoeft niet vanuit EDEN, maar kan ook een script zijn denk ik...

**Comment by WhistleTDNL** [comment]
Als oplossing:

`fn_SelectStartingPoint = {
PRIVATE ["_clicker", "_mapclickparams", "_pos", "_shift", "_alt", "_justPlayers"];
_clicker 		= _this select 0;
_mapclickparams = _this select 1;

_pos   = _mapclickparams select 0;
//_units = _mapclickparams select 1;
_shift = _mapclickparams select 2;
_alt   = _mapclickparams select 3;

if (_shift) then {
	if (visibleMap) then {
		openMap false;
	};
	
	// Remove onMapSingleClick
	onMapSingleClick "";
	
	_justPlayers = allPlayers - entities "HeadlessClient_F";
	
	if (isServer) then {
		// Set players to pos
		{
			_x setposATL _pos;
		} foreach _justPlayers;
	};
};
};`
