### ISSUE TITLE
Zeus voor stafleden

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#39]
Zie $titel, er zou geen aparte module meer nodig hoeven zijn.

**Comment by WhistleTDNL** [comment]
https://forums.bistudio.com/topic/175783-zeus-only-for-admins-need-help/?do=findComment&comment=2754533 kan de oplossing bieden

**Comment by Ligthert** [comment]
Gek genoeg zit dit al in de template kwamen Flendurs en ik gisteravond achter.
