### ISSUE TITLE
Ondersteuning van non-disposable AT

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#40]
De AT4 en RPG-18 werkt perfect met de template_base, maar dit werkt niet met de RPG7 werken omdat deze reusable is en losse rakketjes gebruikt.

Tijd om dit erin te bakken.

**Comment by WhistleTDNL** [comment]
Met Sacha overlegd hierover. De rol medium AT is hiervoor wel geschikt, in de rol Medium AT is het mogelijk om non-disposable AT's te geven en rockets toe te voegen. Dus als men dat wil voor een bepaalde unit, dan moet je de rol medium AT selecteren.

**Comment by Ligthert** [comment]
Aaaaaaaaand does not work as advertised.. :(
