### ISSUE TITLE
Optie om een cargo leeg te hebben

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#42]
Op dit moment kan de cargo van een crate of voertuig:

- Met rust te laten en dat aan Arsenal overlaten oid
- Het op te vullen met een selecteerbare preset

Wat het mist is een preset wat de cargo van de crate of voertuig leegt en dan niks.

**Comment by WhistleTDNL** [comment]
klaar met [deze](https://github.com/Lowlands-Tactical/LT_Template_Base/commit/486d48f09168df8a8296cb6bef8aeaddf72d957d) commit
