### ISSUE TITLE
[Feature] set gear module - Instelbare hoeveelheid magazijnen

### ISSUE THREAD

**Issue by PingWing1337** [Lowlands-Tactical/LT_Template_3G.VR#44]
PingWing, waarom gebruik je niet de setGear module?
Mocht er wat veranderen, dan zit je niet aan Arsenal vast en blijft de missie gewoon werken.

Ok, PingWing maakt wel gebruik van de setGear module...

Maar ja, toen gaf ik een wat passend marksman-rifle en passende AT en kwam ik er achter dat ik niet kon instellen hoeveel magazijnen je hiervan krijgt... leuk voor de AT-4, wat minder leuk voor de RPG als je maar 1 magazijn in je rugzak krijgt.

**Comment by Ligthert** [comment]
PingWing,

Zoals je misschien terug hebt gelezen hebben @WhistleTDNL en ik besloten dit ticket af te wijzen.

Dit heeft de volgende redenen:
- Het is ontzettend veel werk voor iets wat een kleine impact zal hebben of bestaande scenario's en toekomstige scenario's.
- De complexiteit wat hiermee gepaard gaat. Effectief zal ieder wapen iets van 6 configuratie punten hebben om te configureren.

Betreft de voorbeelden die je gaf: voor de RPG, hiervoor dien je de MAT te gebruiken. Deze heeft zowel een tube als de rpgs die daarbij gepaard gaan. Dit is wat ik nu ook gebruik voor alle units met WARSAW PACT wapens. Zie hiervoor ticket #40 

Voor vragen kan je bij mij terecht.
