### ISSUE TITLE
AutoZone v1.5 maken

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#49]
AutoZone v1 is fantastisch! Maar heeft z'n gebreken. Tijd om deze eens te vervangen.

- [ ] Nieuwe module maken, oude hiden
- [x] plaatsing van voertuigen minder random doen zodat ze veilig spawnen zonde te exploden
- [x] allowcrewimmobile op voertuigen gooien om met spelers te fucken
- [ ] trigger-based module maken.

**Comment by WhistleTDNL** [comment]
done met [deze](https://github.com/Lowlands-Tactical/LT_Template_Base/commit/589cec10528ed780611c934b828377158dd86005) commit
