### ISSUE TITLE
Group en member markers inbouwen

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#50]
Kijken of dit van F3 of Hull overgenomen kan worden zonder dat dit backwards compatibility breekt.

**Comment by Ligthert** [comment]
Dit implementeren nadat CBA z'n _group names in lobby_ update uit heeft.

**Comment by Ligthert** [comment]
Hoe ik me dit voor me zie:
- Als eerste parameters voor in de lobby waarin de missiemaker de defaults kan instellen in het geval dat die geen markers wil
- Er zijn twee groepen aan markers: groups en group members
- Alle markers zijn local ( zie: https://community.bistudio.com/wiki/createMarkerLocal ) om onnodig network traffic en in het geval van TvT leakage van Intel te voorkomen.
- Voor group member markers is dit een `foreach` door `units player` en alles een marker geven, of een marker verplaatsen en de direction inzetten. Dit is niks anders dan elke x seconden kijken hoe je groep eruit ziet. Nieuwe teammember? Marker maken (marker naam is naam van speler?) en deze naam in een array douwen. Speler dood/weg? Marker verwijderen en deze uit array halen.
- Group markers de kleur van de factie en als het kan met de gepaste NATO logo (bijv \A3\ui_f\data\map\markers\nato\n_inf.paa)

De vraag wat ik heb hoe dat zit met backwards compatibilty. Doen of niet doen?
Met detectie van de type unit automatisch zijn of moet dit per groep opgegeven worden?

**Comment by WhistleTDNL** [comment]
Het zou mooi zijn als je vanaf een bepaald zoomlevel pas per unit een marker ziet en anders 1 marker

**Comment by Ligthert** [comment]
1 marker is er al, dat is de groupmarker.
Verder blijft alle group members als marker zichtbaar wel een requirement. Het is wel iets wat je optioneel kan maken in de params.

**Comment by Ligthert** [comment]
Je kan vanuit EDEN een callsign instellen, dat is je group ID en nog wat andere dingen.. 
Broncode is dit https://github.com/CBATeam/CBA_A3/blob/master/addons/common/fnc_setCallsign.sqf
Nu kijken hoe dit uitgelezen kan worden per _group_.

**Comment by Ligthert** [comment]
Na enige discussie zijn de reacties tegen dit voorstel of neutral of negatief. Dit ticket kan dus dicht.
