### ISSUE TITLE
Spec-ops loadouts toevoegen

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#51]
Voor onze MILSIM behoeftes wordt het tijd om tijd om specops toe te voegen gezien de huidige units niet volstaan qua loadout en behoeften.

De volgende klasses hebben liefde nodig:

- [ ] SQL/FTL
- [ ] Medic
- [ ] DemSpec
- [ ] comSpec ( glorified UAV Operator )
- [ ] Operator

**Comment by Ligthert** [comment]
Voordat we aan de slag gaan met #53 dan moet dit al beschikbaar zijn omdat het super ruk gaat zijn om retroactief nog allerlei loadouts aan te passen omat er ineens 5 nieuwe units erbij zijn die compleet anders zijn.

**Comment by WhistleTDNL** [comment]
OBV onderstaande quote ticket gesloten: 

> [13:08] Sacha: Yep. Sluit het ticket. Skip....
