### ISSUE TITLE
Wapen presets vanuit het menu kunnen selecteren.

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#53]
Nu kunnen we camo's selecteren! Nu nog groepen van wapens. :)

- [ ] Default (LT NLD)
- [ ] US80s
- [ ] US90/00
- [ ] US2010
- [ ] RU70
- [ ] RU90
- [ ] RU2010
- [ ] Politie
- [ ] Rebellen
- [ ] Brits
- [ ] PMC (Black SCAR)
- [ ] Interventie (MP-5, M21 / M14, allemaal met silencers)
- [ ]

**Comment by PingWing1337** [comment]
- [ ] Brits (XM-8 serie)
- [ ] Interventie (MP-5, M21 / M14, allemaal met silencers)
- [ ] "Murican (M4a1, M249 SAW, M21)

**Comment by Ligthert** [comment]
Ik heb PingWing zijn toevoegen verwijderd omdat het verwarring veroorzaakt.

De lijst hierboven is een suggestie, nothing is set in stone en ik wil hier met de missiemakers ff naar kijken wat wijsheid is.

**Comment by WhistleTDNL** [comment]
Mijn rol is klaar. Nu nog zorgen dat de gear per set wordt geplaatst in een bestandje.

**Comment by WhistleTDNL** [comment]
Gisteren 25 loadout presets gemaakt. Nu inladen in de repo en gear_combo.hpp fitten.
Volgorde van initialisatie moet ook ietsjes anders gaan worden, zie onderstand:

> Dus de vervolg stappen zijn:
1) strip #include customGear.sqf uit init.sqf van de template
2) zorg dat customGear.sqf uitgevoerd wordt door het framework

Met als beoogde effect:
Dat de globale variabelen afgehandeld worden in de volgende volgorde:
1) loadouts
2) customGear.sqf
3) setItems.sqf

**Comment by WhistleTDNL** [comment]
Loadouts zitten erin en initialisatie van customGear.sqf is nu na initialisatie van Loadouts.
Dropdown menu zou nu de juiste files moeten starten. Binnenkort testen met clanmembers.

**Comment by WhistleTDNL** [comment]
Als we de volgende rollen testen dan zijn alle verschillende combinanties getest:
Rollen:
rifle	// Medium MG assistant
carbine	// Rifleman AT
gl		// Teamleader
sam		// Medium SAM Gunner
mat		// Medium AT Gunner
hat 	// Heavy AT Gunner
mg		// Automatic Rifleman
mmg		// Medium MG Gunner	
hmg		// Heavy MG gunner (Static)
hmgast  // Heavy MG assistant gunner (Static)
mort	// Mortar gunner (Static)
mortast // Mortar assistant gunner (Static)
smg		// Crewman
dm 		// Designated marksman
sn		// Sniper

Waar we op moeten testen is het volgende: 
Script-errors
Granaat
Magazijnen (tracer/non-tracer) werkend op wapen
GL granaten werkend op wapen
Rockets van AT/SAM werkend op wapen
Attachments werkend op wapen

**Comment by WhistleTDNL** [comment]
dit zit nu in de modset. Wat mij nu nog rest is eventuele problemen die ik niet heb gezien. Daarvoor graag aparte tickets aanmaken.
