### ISSUE TITLE
Gear-script uitzonderingen laten maken afhankelijk van het AT wapen

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#55]
AT4 = Disposable, maar 1tje geven
RPG = Reusable, 1tje geven + x rakketjes.
Deze intelligentie inbouwen in het gear script en we krijgen betere russen! :D

**Comment by WhistleTDNL** [comment]
Done

**Comment by WhistleTDNL** [comment]
De aantallen mams die worden gegeven aan een rat/mat/hat rol zijn nog niet afgestemd met de staf. Ik wijs dit daarom aan een staf lid toe om uit te zoeken wat een goed aantal raketten is per rol.

**Comment by Ligthert** [comment]
@WhistleTDNL is dit inmiddels af en getest en kan dit dicht?
