### ISSUE TITLE
Herbevoorrading inbouwen

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#61]
Af en toe komt het wel eens voor dat we te weinig ammo hebben en dan is een paradrop gewenst in het geval dat er geen voortuig is met ammo oid.

Vraag is nu om:
- Voeg een item toe aan de admin/staff menu (https://github.com/Lowlands-Tactical/LT_Template_Base/blob/master/admin/init.sqf)
- Zorg dat het de user een map positie aan laat klikken:
> openMap[true,true]; onMapSingleClick "##MAGIC HERE##; openMap[false,false]; onMapSingleClick ''; ";
- Maak een crate, leeg deze en geeft het content aan de side van de caller (Lt_fnc_setvehicle )
- attachTo een parachute, smoke en een chemlight ( zie ook https://github.com/Lowlands-Tactical/LT_Template_Base/blob/master/scripts/paradrop.sqf)

**Comment by WhistleTDNL** [comment]
is afgelopen woensdag opgeleverd.
