### ISSUE TITLE
Smootch verwijderen uit Admin scripts

### ISSUE THREAD

**Issue by WhistleTDNL** [Lowlands-Tactical/LT_Template_3G.VR#62]
[hier](https://github.com/Lowlands-Tactical/LT_Template_Base/blob/master/admin/init.sqf#L5) en [hier](https://github.com/Lowlands-Tactical/LT_Template_Base/blob/master/briefing/admin.sqf#L3) moet het ID "76561198007493141" worden weggehaald.

**Comment by Ligthert** [comment]
Done and Done
