### ISSUE TITLE
setVehicleGear side kiezen

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#63]
setVehicleGear neemt nu standaard WEST als er iet niet binnenkomt via de functie. Dit moet anders, mogelijk opties zijn:

- class van de voertuig uit de config trekken, dan de site en dat nemen als side.
- kijken naar de requestor?
- Een ander magische oplossing.

**Comment by WhistleTDNL** [comment]
done
