### ISSUE TITLE
Backwards compatibility issue met Passing Through

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#67]
Fallback naar NLD Units uniform ipv Yankistan uniforms.

**Comment by WhistleTDNL** [comment]
Helm van deze camoset was niet ingevuld. Gefixt met [deze](https://github.com/Lowlands-Tactical/LT_Template_Base/commit/a084f7c6acffbc331eb8300e4418952eb3534a12) commit
