### ISSUE TITLE
NVG / Flashlight bij custom gear

### ISSUE THREAD

**Issue by PingWing1337** [Lowlands-Tactical/LT_Template_3G.VR#70]
Standaard krijgen units een NVG wanneer deze optie aan staat. Zelfs wanneer custom gear **uit** staat.

Wanneer er in de missie parameters gekozen wordt voor NVG's: YES dan krijgen units deze ongeacht of ze ge-exclude van de camo settings zijn.

Doe je NVG's uit (bij de parameters), dan volgt het probleem dat units standaard flashlights krijgen. Niet al te handig in combinatie met CSAT's VIPER uniformen. 

**Oplossing**
Extra parameter voor proberen toe te dienen van Flashlights aan wapen, deze keuze niet relateren aan de "NVG Optie".
Daarnaast ook geen NVG's toedienen aan units welk van de camo settings ge-exclude zijn.

**Comment by WhistleTDNL** [comment]
done met [deze](https://github.com/Lowlands-Tactical/LT_Template_Base/commit/373fded89160b822aed570c1412b82303a4f7e04) commit
