### ISSUE TITLE
Preset AAF, CSAT, FIA - Light Anti Tank = Heavy AT

### ISSUE THREAD

**Issue by PingWing1337** [Lowlands-Tactical/LT_Template_3G.VR#73]
De LAT (normale Anti-Tank) heeft een zwaar, long-range AT weapon (Titan).
Zou dit gewoon een NLAW kunnen worden zoals ze standaard ook hebben.
MAT & Heavy AT hebben al de Titan.
Geldt voor: 
https://github.com/Lowlands-Tactical/LT_Template_Base/blob/master/gear/Loadouts/CSAT_2035_QBZ.sqf
https://github.com/Lowlands-Tactical/LT_Template_Base/blob/master/gear/Loadouts/AAF_2035.sqf
https://github.com/Lowlands-Tactical/LT_Template_Base/blob/master/gear/Loadouts/CSAT_2035_KAT.sqf
https://github.com/Lowlands-Tactical/LT_Template_Base/blob/master/gear/Loadouts/FIA_2035.sqf
https://github.com/Lowlands-Tactical/LT_Template_Base/blob/master/gear/Loadouts/NATO_2035_MX.sqf
https://github.com/Lowlands-Tactical/LT_Template_Base/blob/master/gear/Loadouts/NATO_2035_SIG.sqf

**Comment by WhistleTDNL** [comment]
gefixt met [deze](https://github.com/Lowlands-Tactical/LT_Template_Base/commit/b43a5ddec8bf5e93e19669b21a0d7f5611693815) commit
