### ISSUE TITLE
Briefing.

### ISSUE THREAD

**Issue by Ligthert** [Lowlands-Tactical/LT_Template_3G.VR#8]
Er moet een briefing komen.

**Comment by Ligthert** [comment]
Dankzij commit 45745b09ab251e0138223333a1d3f2f4139ad006 is er nu een briefing. 2 modules en standaard zaken.

Wat nog mist is een functionele admin gedeelte. ( WIP )

**Comment by WhistleTDNL** [comment]
- [ ]  in admingedeelte ook fatigue on/off zetten.

**Comment by WhistleTDNL** [comment]
het admingedeelte is geimplementeerd en het is bewezen dat het werkt,
